# Generated by Django 3.2.5 on 2021-10-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20211013_1906'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
    ]
