# Generated by Django 3.2.5 on 2021-10-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='orderItem',
        ),
        migrations.AlterModelTable(
            name='orderstatus',
            table='srderstatus',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='promotion',
        ),
    ]
