# Generated by Django 3.2.5 on 2021-10-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20211013_1910'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderstatus',
            table='orderstatus',
        ),
    ]
